<div class="font-size">1. INTRODUCTION</div>
<p class="w3-text-white font-size1 font-size14">This Privacy Policy covers the information Biocine Entertainment, its group companies or affiliates (“JEEOGURU” and/“We”/Our/Us”) collects from the User(s) (“User(s)” and/or “You/Your”) of www.jeeoguru.com or JEEOGURU application (Android/ IOS/ Apple TV, Amazon Fire TV, Roku TV) (“Platform”) for the services provided by JEEOGURU on the Platform (as defined in the Terms of Use of the Platform). This Privacy Policy explains our practices, including Your choices, regarding the collection, Use, and disclosure of certain information, including Your personal information by JEEOGURU. You can choose not to provide certain information, but you may not be able to enjoy all the features of our Platform and services provided by JEEOGURU. Personal Information we learn from you helps us to personalize and continually improve your online experience.
This Privacy Policy should be read in conjunction with the Terms of Use available on the Platform. You understand that the terms ‘Personal Information’, ‘Sensitive Personal Data’, and ‘Information’ shall have the meaning ascribed to them under the applicable laws in India. Your Personal Information is collected if You register with the Platform. Upon registration, You gain access to the Platform or take any action on the Platform or Use or access the Services as defined in the Terms of Use.
Your Use of Our services offered on the Platform is constructed to mean that You consent to our collection, storage, processing and transfer of Your Personal Information and/or Sensitive Personal Data and/or Information in accordance with this Privacy Policy and You consent to the terms and conditions of this Privacy Policy.
Please note that JEEOGURU is the Data Controller of your personal data. The principles set out in this Privacy Policy apply to all instances in which JEEOGURU receives your personal data as a Data Controller for the purposes described in this policy.
</p><p class="w3-text-white font-size1 font-size14">Here are our privacy principles- Providing information to us is your choice.
</p><p class="w3-text-white font-size1 font-size14"> Information collected shall be used lawfully, fairly and in a transparent way.
</p><p class="w3-text-white font-size1 font-size14"> Collected only for valid purposes that we have explained to you and not used in any way that is incompatible with those purposes.
</p><p class="w3-text-white font-size1 font-size14"> Information collected shall be recorded and preserved for operational purposes unless You request to delete the same.
</p><p class="w3-text-white font-size1 font-size14">Accurate and kept up to date.
</p><p class="w3-text-white font-size1 font-size14">Kept only as long as necessary for the purposes required.
</p><p class="w3-text-white font-size1 font-size14">You shall have the choice to delete the information collected by Us or by any other third party Service Providers or receive any communication JEEOGURU through the steps mentioned in Point No. 8
</p>
 

<div class=" font-size1 font-size16">2. INFORMATION WE COLLECT</div>
<p class="w3-text-white font-size1 font-size14">2.1 Information You Give Us:
	<br />
When you use the Platform, for example to register to create an account, update your information, sign up for a subscription, use certain features, access or download content, purchase items or enter into promotions, refer others to the Platform, interact with us via third party application or social media sites, request customer support or otherwise communicate with us, we or our service providers or business partners may collect information that relates to you, including personal information, such as your name, e-mail address, telephone number, mobile phone number, credit card or debit card details, geographic location, social media account details and other information from your device.
You may decide to provide us with another person's email or phone number so that person may be invited to join JEEOGURU or so that we may facilitate your communication with other people through the service. Local law may require you to seek the consent of your contacts to provide their personal information to JEEOGURU, who may use that information in accordance with the terms of this Privacy Policy.
</p><p class="w3-text-white font-size1 font-size14">2.2 Information Collected Automatically<br />
Whenever you visit or interact with the Platform through the www.jeeoguru.com, JEEOGURU application (accessible through various third party Android/ IOS/ Apple TV, Amazon Fire TV, Roku TV), JEEOGURU, as well as any third-party advertisers and/or service providers, may use a variety of technologies that automatically or passively collect information about how the Platform is accessed and used. Usage Information may include information collected in the following ways:
<p class="w3-text-white font-size1 font-size14">a. Log Files: Information is logged about your use of the Platforms, including your browser type, operating system, activations, content you access, download, access and listening/viewing times, the page served and the preceding page views. This statistical usage data provides us with information about the use of the Platform, such as how many visitors visit a specific page on the Platform, how long they stay on that page, and which hyperlinks, if any, they "click" on. It also provides us with information about your interactions with movies, Web Series, Shorts, Songs, Playlists, Audio-Visual content and other JEEOGURU users, as well as advertising and products or services offered through or linked from the Platform. This information helps us keep our Platform fresh and interesting to our visitors and tailor content to a visitor’s interests.
</p><p class="w3-text-white font-size1 font-size14">b. Location Information: We may collect information about the location of your device when you access or use the Platform; or if you choose to turn on your Bluetooth, Wi-Fi or other Geolocation functionality when you use the App, subject to your consent, the App may collect and use your Geolocation information. We may share your location with certain third-parties for analytics and advertising purposes.
</p><p class="w3-text-white font-size1 font-size14">c. Device Identifiers: JEEOGURU may automatically collect your IP address or other unique identifier ("Device Identifier") for the computer, mobile device, tablet or other device (collectively, "Device") you use to access the Platform, including the hardware model and mobile network information. A Device Identifier is a number that is automatically assigned to your Device when you access a web site or its servers, and includes AD-IDs or IDFAs, and our computers identify your Device by its Device Identifier. We may use a Device Identifier to, among other things, administer the Platform, help diagnose problems with our servers, analyse trends, track users’ web page movements, help identify, and gather broad demographic information for aggregate use.
</p><p class="w3-text-white font-size1 font-size14">d. Cookies: Pixel Tags: The technologies used on the Platform to collect Usage Information, including Device Identifiers, may include but are not limited to: cookies (data files placed on a Device when it is used to visit the Platform), mobile analytics software and pixel tags (transparent graphic image, sometimes called a web beacon or tracking beacon, placed on a web page or in an email, which indicates that a page or email has been viewed). Cookies may also be used to associate you with social networking sites and, if you so choose, enable interaction between your activities on the Platform and your activities on such social networking sites. We, or our vendors, may place cookies or similar files on your Device for security purposes, to collect information enabling digital rights management, to facilitate site navigation and to personalize your experience while visiting our Platform (such as allowing us to select which content is most likely to appeal to you, based on your interests, preferences, location, or demographic information). Personalized content may also include content from the providers of goods and services that you may be able to purchase through the Platform or otherwise (who may pay us to show you such content).
Cookies are used for marketing activities (such as but not limited to sending push notifications, emails, SMS), analytics, improving user experience (such as but not limited to through conversion rates, viewing patterns, click-through) and user preferences (such as but not limited to language settings, browsers).
</p><p class="w3-text-white font-size1 font-size14">e. Advertising Id: Advertising identifiers are similar to cookies and are found on many mobile devices and tablets, and certain streaming media devices. Like cookies, advertising identifiers are used to make online advertising more relevant. We are taking your consent to allow any third party advertisers to analyse and perform contextual advertising, frequency capping, conversion tracking, reporting and security and fraud detection. This can be done using persistent device identifier (for example: SSAID, MAC address, IMEI, etc.) for which we are taking your consent. This is a user-resettable identifier and will be used for further Ads use-cases
Also, we may use analytics platforms and other tracking technologies to help us track and analyse usage of our Platform, using cookies, pixels and other tracking technologies.
</p><p class="w3-text-white font-size1 font-size14">2.3 Information Received from Other Sources
	<br />
We also may obtain information from other sources and combine that with information we collect through the Platform. For example, if you create an account using your credentials from a third-party websites (such as but not limited to Google, Facebook and others), we will have access to certain information from that site, such as your name, profile and account information, such as lists of your friends, "likes", comments you have shared, groups and location, in accordance with the authorization procedures determined by such third-party social media site. Services like Facebook Connect give you the option to post information about your activities on our Platform to your profile page to share with others within your network. In addition, we may receive information about you if other users of a third party application or website give us access to their profiles and you are one of their "connections" or information about you is otherwise accessible through your "connections'" web page, profile page, or similar page on a social networking or other third party website or interactive service.
You may integrate your JEEOGURU account with third party applications and sites. If you do, we may receive similar information related to your interactions with the Platform on the third party application, as well as information about your publicly available activity on the third party application or site.
We may also receive information about you from our partners and service providers, (including, for example, business partners, analytics vendors and search information providers) which we use to personalize your experience on the Platform.
JEEOGURU never stores, receives or has access to any bank account details, debit card, credit card information from you. Any information stored, received or accessed by JEEOGURU through a payment gateway is limited to your name, number, e-mail and geo location.</p>
<div class=" font-size1 font-size16">3. HOW WE USE THE INFORMATION COLLECTED</div>
<p class="w3-text-white font-size1 font-size14">We may use the information about you for a variety of business purposes, including for example, to:</p>
 <p class="w3-text-white font-size1 font-size14">a. Respond to your questions and requests and provide customer service;
</p><p class="w3-text-white font-size1 font-size14">b. Provide you with access to certain features of the Platform;
</p><p class="w3-text-white font-size1 font-size14">c. Deliver the services you request, process transactions and send you related information;
</p><p class="w3-text-white font-size1 font-size14">d. Verify your identity; communicate with you about your activities on the Platform;
</p><p class="w3-text-white font-size1 font-size14">e. Tailor content, offers and promotions offered by JEEOGURU and others, and provide news and other information we think will be of interest to you;
</p><p class="w3-text-white font-size1 font-size14">f. Perform market research, Platform analytics and operations;
</p><p class="w3-text-white font-size1 font-size14">g. Personalize and improve the Platform and products, services made available on or outside the Platform (including on other sites/ apps that you visit), for example by providing personalized or localized content, recommendations, features, content or features that match your interests and preferences;
</p><p class="w3-text-white font-size1 font-size14">h. Link or combine with information we receive from others to help understand your needs and to provide you with better service;
</p><p class="w3-text-white font-size1 font-size14">i. Contact you with regard to your use of the Platform and interest in certain products and services, and, in our discretion, changes to any JEEOGURU policy;
</p><p class="w3-text-white font-size1 font-size14">j. Communicate with you, either directly or through one of our partners, for marketing and promotional purposes via emails, notifications, or other messages, consistent with any permissions you may have communicated to us; and
</p><p class="w3-text-white font-size1 font-size14">k. For purposes disclosed at the time you provide your personal information or otherwise with your consent.</p>
<div class=" font-size1 font-size16"> 4. SHARING OF INFORMATION</div>
<p class="w3-text-white font-size1 font-size14">The information collected or generated through your use of the Platform may be shared by you or by us as described below.
 <p class="w3-text-white font-size1 font-size14">4.1 Sharing of Information by You<br />
</p><p class="w3-text-white font-size1 font-size14">JEEOGURU is a service that offers many ways to find, enjoy, and share content. Your name and/or username, profile picture, who you follow, your followers, and your JEEOGURU user profile will be publicly available
Third Party Platforms: If your JEEOGURU account is connected to a third party application or social medial platform, JEEOGURU may automatically share your activity with that service, including the content you use and such information may be attributed to your account on the third party platform and published on such service. Likewise, if you log into a third party application with your JEEOGURU account, that third party application may have access to certain information such as your watch list, playlists and any activity. A third party platform’s use of information collected from you (or as authorized by you) is governed by the third party platform’s privacy policies and your settings on the relevant service. In such cases, JEEOGURU shall in no manner be liable for disclosure of information by you to the Third Party.
</p><p class="w3-text-white font-size1 font-size14">4.2 Sharing of Information by Us<br>
</p><p class="w3-text-white font-size1 font-size14">We may share aggregate user statistics, demographic information, and Usage Information with third parties. We may also share your information as disclosed at the time you provide your information, as set forth in this Privacy Policy and in the following circumstances:
Third Parties:
</p><p class="w3-text-white font-size1 font-size14">In order to carry out your requests, to make various features, services and materials available to you through the Platform, and to respond to your inquiries, for data processing and storage we may share your information with third parties that perform functions on our behalf, such as companies that: host or operate our Platform; payment processors; analyse data; provide customer service; sponsors or other third parties that participate in or administer our promotions. Your information may also be used by us or shared with our sponsors, partners, analytics companies or other third parties in connection with marketing, promotional, and other offers, as well as product information, and for such third party’s analytics and market research. These analytics companies use various technologies to collect data in order to cater to your preferences. These technologies may include the placement of cookies or web beacons, the use of unique or non-unique non-personal identifiers, or the use of other technologies on our Platforms, which may be used to track user behaviour, to track how our Platforms are being used, to link various Devices you may use, build consumer profiles. This Privacy Policy does not cover the use of analytics companies. We may also share your information with the rights holders that license content to JEEOGURU to stream on the Platform.
</p><p class="w3-text-white font-size1 font-size14">b. Business Transfers:<br />
</p><p class="w3-text-white font-size1 font-size14">Your information may also be used by us or shared with our subsidiaries and affiliates for internal reasons, primarily for business and operational purposes. As we continue to develop our business, we may sell or purchase assets. If another entity acquires us or all or substantially all of our assets, or assets related to the Platform, your information may be disclosed to such entity as part of the due diligence process and will be transferred to such entity as one of the transferred assets. Also, if any bankruptcy or reorganization proceeding is brought by or against us, all such information may be considered an asset of ours and as such may be sold or transferred to third parties.
</p><p class="w3-text-white font-size1 font-size14">c. Legal Disclosure:<br />
</p><p class="w3-text-white font-size1 font-size14">JEEOGURU may transfer and disclose your information to third parties to comply with a legal obligation; when we believe in good faith that the law requires it; at the request of governmental authorities conducting an investigation; to verify or enforce our Terms of Use or other applicable policies; to respond to an emergency; or otherwise to protect the rights, property, safety, or security of third parties, visitors to our Platform or the public.
</p><div class=" font-size1 font-size16">5. STORAGE AND PROCESSING</div>
</p><p class="w3-text-white font-size1 font-size14">Your information collected by JEEOGURU may be stored and processed in India, United States or any other country in which JEEOGURU or its subsidiaries, affiliates or service providers maintain facilities. JEEOGURU may transfer information that we collect about you, including personal information, to affiliated entities, or to other third parties across borders and from your country or jurisdiction to other countries or jurisdictions around the world.
</p><div class=" font-size1 font-size16">6. DATA SECURITY</div>
</p><p class="w3-text-white font-size1 font-size14">We understand the importance of data security and We want Your experience with Us to be as safe as possible. We have implemented reasonable safeguards and precautions to protect Your Personal Information or Sensitive Personal Data or Information, including technical and organizational measures against unauthorized access, improper Use, alteration, unlawful or accidental destruction, and accidental loss, both in an online and offline context. We have adopted reasonable and best security practices and procedure and We maintain technical and organizational security measures and procedures to protect the security of Your Personal Information or Sensitive Personal Data or Information, which are consistent with measures used by other similar websites. We use an outside platform, and payment processing companies to bill you if you purchase our services. These companies retain, share, store or use your data. However since we do not have access to such information collected by third party payment companies, you are requested to check the privacy policy of such companies to determine how it handles any information it collects from you. 
</p><p class="w3-text-white font-size1 font-size14">Please understand that, while We strive to protect Your Personal Information or Sensitive Personal Data or Information against potential risks and exposures, there is no absolute security in the online sphere. Hence, We ask You to support our IT security efforts by not disclosing any of Your Personal Information or Sensitive Personal Data or Information data on our Platform that is particularly sensitive or not required in the specific context. Furthermore, You can help Us protecting Your personal data by signing off when You finish Using login-protected areas of the Platform.
</p><div class=" font-size1 font-size16">7. DATA RETENTION</div>
</p><p class="w3-text-white font-size1 font-size14">We retain Personal Information or Sensitive Personal Data or Information only for as long as We believe it to be necessary for purposes set out herein for which the Personal Information or Sensitive Personal Data or Information was collected, subject to any legal requirements for the data to be retained for longer periods of time.
</p><div class=" font-size1 font-size16">8. COOKIES</div>
</p><p class="w3-text-white font-size1 font-size14">Cookies are small data files that are commonly stored on Your device (desktop, laptop, mobile, tablet, etc) when You browse and Use the Platform. They are widely Used to make websites work, or to work more efficiently, as well as to provide reporting information and assist with service or advertising personalization. In order for You to have the best experience with the Platform, We Use cookies and other technologies (such as web beacons). For example, We Use cookies and other technologies to make it easy to access Our services by remembering You when You return, to provide and analyze Our services, to learn more about our Users and their likely interests, and to deliver and tailor marketing or advertising.
</p><div class=" font-size1 font-size16">9. DELETING/MODIFYING YOUR INFORMATION</div>
</p><p class="w3-text-white font-size1 font-size14">If You wish to have the Personal Information or Sensitive Personal Data or Information that You have provided to Us deleted, corrected, update out of date or inaccurate information we hold, You can always do so by sending a request to Us on privacy@jeeoguru.com. You may note that deletion of certain Personal Information may lead to cancellation of Your registration with the Platform and/or Your access to certain features of the JEEOGURU can be restricted and may also lead to complete cessation of Your Access to the Platform.
</p><div class=" font-size1 font-size16">10. LINKS TO OTHER SITES/FINANCIAL DATA</div>
</p><p class="w3-text-white font-size1 font-size14">We provide links to other websites and portals such as third party payment gateway providers for Your convenience and information (“Other Websites”). For instance, the JEEOGURU will be Using third party payment gateway providers to process and facilitate the payment of Your Subscription Fee to the JEEOGURU for providing You access to the Subscription. Please note that the JEEOGURU does not directly collect any financial information such as credit card or debit card or net banking details from You. Such other Websites are not controlled by Us. When You visit such Other Website You do so at Your own risk. These other Websites may have their own privacy policies in place, which We recommend You review if You visit any such other Websites. We do not assume any responsibility or liability for such Other Websites, the content of such other Websites and their privacy practices, nor do We endorse them. We encourage You to familiarize Yourself with the privacy statements provided by such other Websites prior to providing them with information about You or entering into any transactions on them.
</p><p class="w3-text-white font-size1 font-size14">While transacting with these Other Websites, You may provide Your financial information including without limitation Your bank account details, credit card account details or Your details pertaining to any payment settlement or pre-paid instrument service provider. You understand, agree and acknowledge that the Platform and JEEOGURU never receives Your financial and payment information from these Other Websites. Your Personal Information, Sensitive Personal Data or Information and financial information will be dealt with by these Other Websites in accordance with their respective privacy policies and other terms and conditions and the JEEOGURU shall not be liable, accountable or responsible for Your Personal Information, Sensitive Personal Data or Information and financial information which You provide to these Other Websites.
</p><div class=" font-size1 font-size16">11. CHILDREN</div>
</p><p class="w3-text-white font-size1 font-size14">You must be 18 years of age or older to subscribe to the Platform. In certain jurisdictions, the age of majority may be older than 18, in which case, You must satisfy that age in order to subscribe to the Platform. While individuals under the age of 18 may utilize the service, they may do so only with the involvement, supervision, and approval of a parent or legal guardian.
</p><div class=" font-size1 font-size16">12. SECURITY</div>
</p><p class="w3-text-white font-size1 font-size14">JEEOGURU uses commercially reasonable security practices and procedures industry practices and procedures designed to help keep Your Personal Information or Sensitive Personal Data or Information safe. Secure server software (SSL) encrypts all information You submit before it is sent to the JEEOGURU. Furthermore, all of the User data We collect is protected against unauthorized access. To prevent unauthorized access, maintain data accuracy, and ensure correct use of information, We employ commercially reasonable and practicable security practices and procedures and security methods and technologies. We will also ensure that any agent or third party that We employ complies with the same security standards as We do for the protection of Your Personal Information or Sensitive Personal Data or Information.
Your information may be transferred to or may be maintained on computers, computer systems and computer resources located outside of Your state or country where the privacy laws may be different (but no less stringent than the restrictions imposed by Indian law) as those where You live. If You are located outside India and choose to provide information to Us, please be aware that the Platform is hosted in India and that JEEOGURU keeps or transfers information to and from India for storage and processing. Your submission of such information represents Your agreement to that transfer.

Unfortunately, the transmission of information over the Internet is not completely secure. Although We strive to protect Your personal data, We cannot guarantee the security of Your data while it is being transmitted to our site; any transmission is at Your own risk. Once We have received Your information, We have commercially reasonable procedures and security practices in place to reasonably endeavor to prevent unauthorized access.
</p><div class=" font-size1 font-size16">13. CHANGES IN PRIVACY POLICY</div>
</p><p class="w3-text-white font-size1 font-size14">From time to time We may update this Privacy Policy. Your continued Use of the Platform and the Services constitutes Your acceptance of the current Privacy Policy and Terms of Use so We encourage You to visit this page periodically to review any changes.
</p><div class=" font-size1 font-size16">14. PHISHING</div>
</p><p class="w3-text-white font-size1 font-size14">Identity theft and the practice currently known as & quot; phishing & quot; are of great concern to the JEEOGURU. Safeguarding information to help protect You from identity theft is a top priority. We do not and will not, at any time, request Your information including Sensitive Personal Data in a non-secure or unsolicited e-mail or telephone communication.
</p><div class=" font-size1 font-size16">15. CONTACT US</div>
</p><p class="w3-text-white font-size1 font-size14">If You have any questions about this Privacy Policy, the practices of JEEOGURU or Your dealings with the Platform, You can contact Us at support@jeeoguru.com or at the Corporate Office: 60/141, Haripada Dutta Lane, Kolkata 700033, West Bengal, India via the links at the bottom of the page.
<br />
Please do not share any private information at the above stated email id support@jeeoguru.com<br />
</p><div class=" font-size1 font-size16">16. GRIEVANCE OFFICER</div>
<p class="w3-text-white font-size1 font-size14">Kousick Mondal shall be the Grievance Officer for the purpose of this Privacy Policy. If You have any questions or grievances or want to delete or modify Your Personal Information, You shall mark Your correspondence to business@jeeoguru.com in the name of Kousick Mondal, Grievance Officer.
Any grievance that We receive from You shall be resolved within a period of one month from the date of receipt of the grievance from You.
Any communication which is not marked as such shall not be treated as a valid and binding communication for the purpose of this Privacy Policy and applicable laws with respect to this Privacy Policy.
</p><p class="w3-text-white font-size1 font-size14">Last Updated: August 1, 2018
</p><p class="w3-text-white font-size1 font-size14">© Biocine Entertainment. All rights reserved.</p>