<div class="font-size">1. INTRODUCTION</div>
<p class="w3-text-white font-size1 font-size14">This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.

</p><p class="w3-text-white font-size1 font-size14">Biocine Entertainment, a company incorporated under the Companies Act, 2013, having its registered office at 60/141, Haripada Dutta Lane, Kolkata, 700033 <strong> (“JEEOGURU”)</strong> owns the domain name <a href="www.jeeoguru.com" class="w3-text-amber"> www.jeeoguru.com </a> (“Website”). The Website allows, upon subscription and payment of necessary subscription fee, users to access and view, inter alia, movies and TV serials, music and videos (“Content”) streamed over the Internet to certain Internet-connected TVs, desktops, laptops, mobiles and other devices.
<br />
Your use of the Website and services and tools are governed by the following terms and conditions, “Terms of Use” as applicable to the Website including the applicable policies which are incorporated herein by way of reference. If You transact on the Website and user interfaces, You shall be subject to the policies that are applicable to the Website and user interfaces, for such transaction. By mere use of the Website and user interfaces, You shall be contracting with JEEOGURU and these terms and conditions including the policies constitute Your binding obligations.
<br />
For the purpose of these Terms of Use, wherever the context so requires “You”, “Your” or “User” shall mean any natural or legal person who has agreed to become a member on the Website and user interfaces, by providing certain information (as detailed in the Privacy Policy) while registering on the Website and user interfaces.
<br />
BY ACCEPTING THESE TERMS OF USE IN ANY MANNER OR ACCESSING THIS WEBSITE AND USERINTERFACES, YOU CONSENT, AGREE AND UNDERTAKE TO ABIDE, BE BOUND BY AND ADHERE TO THE TERMS OF USE and the Privacy Policy accessible at 
<br />
<a href="http://www.jeeoguru.com/terms_condition" class="w3-text-amber">www.jeeoguru.com/terms-of-use </a> and <a href="http://www.jeeoguru.com/privacy-policy" class="w3-text-amber"> www.jeeoguru.com/privacy-policy </a> respectively and any other terms which govern the Website and user interfaces, AND IF YOU DO NOT AGREE TO THESE TERMS OF USE, YOU ARE NOT ENTITLED TO AVAIL OF / USE THE SERVICES AND ANY USE THEREAFTER SHALL BE UNAUTHORIZED.
<br />

</p> 
 
<br />
<div class="font-size1 font-size16">2. DESCRIPTION OF SERVICES AND ACCEPTANCE OF TERMS OF USE</div>
  
<p class="w3-text-white font-size1 font-size14">As stated above, JEEOGURU, through the Website and user interfaces, allows, upon subscription and payment of necessary subscription fee, access and view, inter alia, movies and TV serials, music and videos (“Content”) streamed over the Internet to certain Internet-connected TVs, desktops, laptops, mobiles and other devices.
<br />
JEEOGURU, inter alia, provides an online website <a href="#" class="w3-text-amber"> www.jeeoguru.com </a> as an interactive platform for its viewers and any associated mobile sites, applications to inter alia view films and web series - including trailers, and music and video content including viewing schedules of content offered etc. on the Website and user interfaces, and any other features, tools, applications, materials, or other services offered from time to time by JEEOGURU in connection with its business, provided on the Website and user interfaces, “Content” and includes posting of comments, participation in contests (all such features of the Website and user interfaces, collectively referred to as “Services”.
<br />
Content will be made available to You through different modes, at the discretion of JEEOGURU, including via video on demand basis for viewing at the User’s discretion at a time chosen by You and download for offline viewing by You. Download for offline viewing is for App only. For the Content that will be made available to You, You will be granted a non-exclusive, non-transferable, non-sublicensable, revocable limited license to view the Content for your personal, non-commercial viewing, and that no right, title or interest in any Content will be deemed transferred to You. Please note that both the availability and Your ability to access the Content or some part of Services, (a) is subject to JEEOGURU’s sole discretion and (b) may be dependent upon Your geographical location and (c) is on the condition that not all Content or Services will be available to all viewers. On account of the nature of the Internet, this Website and the Content and Services may also be accessed in various geographical locations; and You hereby agree and acknowledge that You are accessing this Website and availing of the Services, at Your own risk, choice and initiative and You agree and undertake to ensure that Your use of the Website and user interfaces, and the Services complies with all applicable laws including the local laws in Your jurisdiction. Further, such Services and Content may vary from place to place, time to time and device to device and would be subject to various parameters such as specifications, device, Internet availability and speed, bandwidth, etc. You agree and acknowledge that JEEOGURU may monitor or use certain technologies for monitoring of activities including logging of Your IP address to ascertain and verify Your geographical location. To facilitate Your viewership and access, the Services can be packaged by JEEOGURU through different models such as, Content or Services may be accessible (a) free of charge which may include advertisements or commercials or (b) via subscription through payment of a subscription fee with or without advertisements/commercials or (c) a pay-per- view model with or without advertisements/commercials or (d) with a combination of the foregoing on the Website. The Services can be availed through platforms, software and devices, which JEEOGURU approves from time to time, the current list for which is as set out below “Compatible System”. In some cases, whether a device is (or remains) a Compatible System may depend on software or platform provided or maintained by the device manufacturer or other third parties. As a result, devices that are Compatible System at one time may cease to be Compatible System in the future.


</p><p class="w3-text-white font-size1 font-size14">The JEEOGURU website works best with:
<br />
 Latest version of Google Chrome
 <br />
  Latest version of Firefox <br />
 Latest version of Safari <br />
 Latest version of Microsoft Edge <br />
 Microsoft Windows 10 or above <br />
 JavaScript and cookies enabled <br />
 <br />
 The JEEOGURU applications work best with a minimum system requirement of: <br />
 ->  Android Marshmallow v.5.0 or above <br />
 ->  iOS 9 or above <br />
Participation in any contest and or game on the Website conducted by JEEOGURU or viewing of certain Content may be subject to further terms and conditions as may be notified by JEEOGURU from time to time on the Website or otherwise.
</p>
<br />
<div class=" font-size1 font-size16">3. SUBSCRIPTION SERVICES</div>

	 <p class="w3-text-white font-size1 font-size14">
Some of the Content made available on the Website can be availed only by registered Users who have registered under a subscription model (“Registered User”). You may need to register Yourself on the Website and user interfaces, to avail these services on a subscription model (“Subscription”). To become a Registered User, 
You may be required to provide certain personal information to JEEOGURU, including sensitive personal data, and may be required to make payments
 “Subscription Fee” as per the applicable membership plan through a debit card, credit card, internet banking or through, e-prepaid wallet or 
 other payment method accepted by JEEOGURU ”Payment Method” that You opted for during registration. JEEOGURU will be using third party payment gateways to process and facilitate 
 the payment of Your Subscription Fee to JEEOGURU. On successful registration to the Subscription, JEEOGURU will intimate You of the same through e-mail. JEEOGURU may offer different kinds of Subscription plans, each of these Subscription plans being subject to different limitations
  and restrictions and the cost of each of these Subscription plans may vary.
<br />
JEEOGURU shall have the discretion to make certain Content that is a part of the Subscription available to You on more than one end user Compatible System concurrently. JEEOGURU shall also have the discretion to make certain Content that is a part of the Subscription available to You on not more than one end user Compatibility System.
  </p>
  <br />
<div class=" font-size1 font-size16">4. FREE TRIALS </div>
<p class="w3-text-white font-size1 font-size14">Some of the Subscription plans may start with a free trial. The free trial period may last for a period of seven (7) days or such other term as may be determined by JEEOGURU. Your eligibility for a free trial including the time for such free trial and the Content available to be viewed during free trial period is at the discretion of JEEOGURU and such free trial can be modified, suspended or terminated by JEEOGURU at any point of time without giving notice to You. In case You are eligible for any free trial, JEEOGURU may charge You a token amount of money at the time of Your registration for the Subscription plan. This token amount will be refunded to You once JEEOGURU receives the confirmation from the third party payment gateway provider that Your Payment Method has been registered.</p>
<br /> 
<div class=" font-size1 font-size16"> 5.PAYMENTS</div>
<p class="w3-text-white font-size1 font-size14">JEEOGURU will automatically start billing as per Your selected Payment Method for the Subscription plan elected by You at the time of registration through the third party payment gateway at the end of the free trial period, if applicable unless You cancel the Subscription before the end of the free trial period. The cancellation of the Subscription can be done through the ”My Account” section of the Website. It may take a few days for Your payment made to JEEOGURU to be reflected in your “My Account” section.
	<br />
In case You cancel Your Subscription before the end of the free trial period, You will not be entitled to any compensation monetary or otherwise from JEEOGURU for the unutilized period of free trial.
<br />
You cannot change your Payment Method during the tenure of your Subscription. If Your selected Payment Method is no longer available or expires or Your Payment Method fails for whatsoever reason, You will be responsible and liable for any uncollected amounts and JEEOGURU reserves the right to terminate the Subscription offered to You.
<br />
The Subscription Fee will be billed at the beginning of Your membership or at the end of free trial period, as applicable and on each subsequent renewal automatically (as per the Subscription plan chosen by You) unless and until You cancel Your Subscription or the Subscription is otherwise suspended or discontinued pursuant to these Terms. To see the commencement date for Your next renewal period or to cancel Your subscription to the Subscription, You need to visit the “My Account” section on Your profile page. On cancellation of Subscription You will be notified by JEEOGURU.	
<br />

JEEOGURU will be automatically billing as per Your Payment Method for each Subscription period on a monthly basis. However, if You change Your membership plan, this could result in changing the day on which You are billed and the amount which You are billed.	
<br />
In case of change in the Subscription Fee for a particular membership plan that is already opted by You, JEEOGURU will give You an advance notice of these changes.
<br />
The Subscription Fees specified for each Subscription plan are inclusive of applicable taxes. The Subscription Fees billed are non-refundable irrespective of whether the Subscription has been availed by You or not.
<br />
Any changes in the Subscription Plan opted by You is effective only after the expiry of the current Subscription period for which You have already been billed. Accordingly, the Subscription as per revised plan opted by You shall be effective only after the expiry of the then current Subscription period.
<br />
Any request for change or cancellation in any Subscription plan prior to the expiration of the current Subscription plan period will not entail You with a refund for any portion of the Subscription Fee paid by You for the unexpired period.
<br />
You also understand and acknowledge that JEEOGURU only facilitates the third party payment gateway for processing of payments. This facility is managed by the third party payment gateway provider and You are required to follow all the terms and conditions of such third party payment gateway provider.

<br />
You are responsible for the accuracy and authenticity of the information provided by You, including the bank account number/credit card details and the like. You agree and acknowledge that JEEOGURU shall not be liable and in no way be held responsible for any losses whatsoever, whether direct, indirect, incidental or consequential, including without limitation any losses due to delay in processing of payment instruction or any credit card fraud.

<br />
You can access the status of Your Subscription anytime through the “My Account” section on the “Settings” page.
<br />
You can file any complaint related to payment processing on the Website or user interfaces, and the same will be forwarded to the concerned third party payment gateway provider for redressal.
<br />
Upon payment through any of the payment modes, a confirmation of receipt of such payment from the payment gateway provider, an invoice will be made available to You, if applicable.
<br />
Upon payment being received by JEEOGURU through any of the payment method(s), JEEOGURU shall make the Subscription available to You through any of the approved modes of delivery that JEEOGURU adopts.

<br />
It is hereby clarified that the Subscription offered to You is by JEEOGURU and not by any third party including any payment gateway service providers.
<br />
JEEOGURU reserves the right to change, terminate or otherwise amend the Subscription plans, Subscription Fees for the Subscription and billing cycles at its sole discretion and at any time. Such amendments shall be effective upon posting on the Website and Your continued use of the Service shall be deemed to be Your conclusive acceptance of such amendments.

<br />
JEEOGURU reserves the right to change, supplement, alter or remove any of the Content that is subject to a Subscription Fee as it deems fit. JEEOGURU does not guarantee the availability of a specific Content or a minimum Content that is subject to a Subscription Fee.
<br />
Post-Cancellation of Your Subscription, if you wish to re-subscribe to the Subscription, you may do so from the Website and user interfaces.
	</p>
  <br />
  
  
  <div class=" font-size1 font-size16">6. ELECTRONIC COMMUNICATIONS</div>
  <p class="w3-text-white font-size1 font-size14">
  	When You use/avail the Services or send any data, information or communication to JEEOGURU, You agree and understand that You are communicating with JEEOGURU through electronic media/records and You consent to receive communications via electronic records from JEEOGURU periodically and as and when required. JEEOGURU will communicate with You by email or any push or other message or electronic records on the email address and or mobile number available with JEEOGURU or made available to JEEOGURU through a partner which will be deemed adequate service of notice / electronic record.
<br />
You give consent to JEEOGURU and / or its respective affiliates and partners contacting You using the contact information You have provided to JEEOGURU at any time during Your association with JEEOGURU for any purpose including but not limited to:
<br />
 To obtain feedback regarding the Service;  <br />
 To contact you for offering new products or services, whether offered by us, or our respective affiliates or partners.
 <br />	
 You acknowledge and agree that You may be contacted for the above purposes, using any of the contact details provided by You, including via emails, text messages or phone calls. In the event You have indicated any “do not disturb” preferences to Your telecom service provider, and registered Yourself on the national customer preference register / “do not disturb”; or similar list, You are requested to ensure that Your registered preferences allow for communications to be sent to You in accordance with the above provisions.
 <br />
 The Content contained in the Services including but not limited to on the Website is protected by copyright, trademark, patent, trade secret and other laws, and shall not be used except as provided in these Terms and Conditions, without the written permission of JEEOGURU.
 
  </p>
  
 <br /> 
 <div class=" font-size1 font-size16">7. USER COMMITMENT</div> 
<p class="w3-text-white font-size1 font-size14">
	By agreeing to use/avail the Services:
<br /> 
 You confirm that all the data and information supplied by You when You register (“Registration Data”) and provided by You to JEEOGURU and or any JEEOGURU affiliates, distributors is true, current, complete and accurate in all respects.
<br /> 
 You agree to promptly update Your Registration Data so that Your information remains true, current, complete, and accurate at all times.
<br /> 
 You acknowledge and agree that Your Registration Data and any other personal data collected by JEEOGURU is subject to JEEOGURU’s Privacy Policy. For more information, view the full Privacy Policy. JEEOGURU may collect information such as occupation, language, PIN code, area code, unique device identifier, location, and the time zone where the Services are used and may use these to target advertising and make content recommendations.

<br /> 
You acknowledge, consent and agree that JEEOGURU may access, preserve, transfer and disclose Your account information and/or User Material subject to the Privacy Policy, if required to do so by law to co-operate with mandated government and law enforcement agencies or to any private parties by an order under law for the time being in force to enforce and comply with the law including to various tax authorities upon any demand or request by them or in a good faith belief that such access, preservation, or disclosure is reasonably necessary to: (a) comply with legal process and/or any applicable law in the territory; (b) enforce the Terms and Conditions; (c) respond to Your requests for customer service; or (d) protect the rights, property or personal safety of JEEOGURU, affiliates, its users and the public.
 <br /> 
 You agree that JEEOGURU has the right to temporarily suspend access to the whole or any part of the Services for any technical/operational reason and shall be under no liability to You in such an event. JEEOGURU may, but shall not be obliged to, give You as much notice of any interruption of access to the Services as is reasonably practicable. JEEOGURU will restore access to the Services as soon as reasonably practicable after temporary suspension.

 <br /> 
  You agree that JEEOGURU shall be under no liability whatsoever in the event of non-availability of the Website or any portion thereof occasioned by Act of God, war, disease, revolution, riot, civil commotion, strike, lockout, flood, fire, satellite failure, failure of any public utility, man-made disaster, satellite failure or any other cause whatsoever beyond the control of JEEOGURU.

 <br /> 
 You acknowledge and agree not to either directly or through the use of any device, software, internet site, web-based service, or other means remove, alter, bypass, avoid, interfere with, violate, or circumvent any patent; trade secret; copyright, trademark, or other proprietary notice marked on the Content or any digital rights management mechanism or device; any content protection or access control measure associated with the Content, including geo-filtering mechanisms; privacy; publicity; or other proprietary right under applicable law.

<br /> 
   You agree not to either directly or through the use of any device, software, internet site, web- based service, or other means copy, download, capture, reproduce, duplicate, archive, distribute, upload, publish, modify, translate, broadcast, perform, display, sell, transmit or retransmit the Content or create any work or material that is derived from or based on the Content. This prohibition applies regardless of whether such derivative works or materials are sold, bartered, or given away.

<br /> 
    You agree that JEEOGURU and/or its affiliates own and/or retains all rights to the Services and the Content throughout the territory of the world in perpetuity. You further agree that the Content You access and view as part of the Services is owned or controlled by JEEOGURU, its affiliates and or its licensors. The Services and the Content are protected by copyright, trademark, trade secret, and other intellectual property laws.
<br /> 	
     Except as provided in these Terms of Use (or otherwise expressly provided by JEEOGURU), You may not copy, download, screen capture, reproduce, duplicate, archive, upload, modify, translate, publish, broadcast, transmit, retransmit, distribute, perform, display, sell, frame or deep-link, make available, or otherwise use any Content contained in the Services. You further agree not to use the Services to:
<br /> 	
Post, upload or otherwise transmit or link to Content that is: unlawful; threatening; abusive; obscene; vulgar; sexually explicit; pornographic or inclusive of nudity; offensive; excessively violent; invasive of another’s privacy, publicity, contract or other rights; tortious; false or misleading; defamatory; libelous; hateful; or discriminatory;
<br /> 	
Harass or harm another person;
<br /> 	
Exploit or endanger a minor;
<br /> 	
Impersonate or attempt to impersonate any person or entity;
<br /> 
Violate any patent, trademark, trade secret, copyright, privacy, publicity or other proprietary right;

<br /> 
Introduce or engage in activity that involves the use of viruses, software disabling codes, bots, worms, or any other computer code, files or programs that interrupt, destroy, or limit the functionality of any computer software or hardware or telecommunications equipment, or otherwise permit the unauthorized use of or access to a computer or a computer network;

<br /> 
Attempt to decipher, decompile, disassemble or reverse-engineer any of the software, applications and/or any element comprising the Website, the application for accessing the Content, or the JEEOGURU Services;

<br />
Interfere with, damage, disable, disrupt, impair, create an undue burden on, or gain unauthorized access to the JEEOGURU Services, including Biocine Entertainment’s servers, networks or accounts;Cover, remove, disable, manipulate, block or obscure advertisements or other portions of the Content;
<br /> 
Delete or revise any information provided by or pertaining to any other user of JEEOGURU.
<br />Further, You agree not to
<br />
Use technology or any automated system such as scripts, spiders, offline readers or bots in order to collect or disseminate usernames, passwords, email addresses or other data from JEEOGURU, or to circumvent, delete, deactivate, decompile, reverse engineer, disassemble or modify any security technology or software that is part of the JEEOGURU or the Website;
<br />
Send or cause to send (directly or indirectly) unsolicited bulk messages or other unsolicited bulk communications of any kind through JEEOGURU. If You do so, You acknowledge You will have caused substantial harm to JEEOGURU, but that the amount of harm would be extremely difficult to measure. As a reasonable estimation of such harm, and by way of liquidated damages and not as a penalty, You agree to pay JEEOGURU INR 500 (Indian Rupees five hundred only) for each actual or intended recipient of such communication without prejudice to any other rights of action that JEEOGURU may have against You in law or equity;
<br />
Solicit, collect or request any personal information for commercial or unlawful purposes;
<br />
Engage in commercial activity (including but not limited to advertisements or solicitations of business; sales; contests; sweepstakes; creating, recreating, distributing or advertising an index of any significant portion of the Content; or building a business using the Content) without Biocine Entertainment’s prior written consent;
<br />
Use technology or other means to access, index, frame, or link to the Website (including the Content) that is not authorized by JEEOGURU;
<br />
Access the Website (including the Content) through any automated means, including “robots”, “spiders”, “offline readers” (other than by individually performed searches on publicly accessible search engines for the sole purpose of, and solely to the extent necessary for, creating publicly available search indices – but not caches or archives – of the Website and excluding those search engines or indices that host, promote, or link primarily to infringing or unauthorized content);
<br />
Use the Services to advertise or promote competing services;
<br />
Use the Services in a manner inconsistent with any and all applicable law;
<br />
Attempt, facilitate, induce, aid and abet, or encourage others to do any of the foregoing.
<br />
 You agree that Your use of the Services and the Content may give You the opportunity to view, publish, transmit, submit posts and/or comment in accordance with these Terms and Conditions. You agree that You will not misuse the Content and/or other user material You access and view as part of the Service, including without limitation, download/store the Content by illegal/non-permitted means, or infringe any of JEEOGURU’s / or its licensor’s copyright, trademark, and other intellectual property including any rights.
<br /> 
- You further agree that You shall not post, publish, transfer, upload, transmit or submit any of the Content, including without limitation videos, images, comments, User Material (defined below) or articles, of the Website on any other website, webpage or software, whatsoever which is not owned by JEEOGURU.
<br />
 You agree that the Content provided on the Website is strictly for Your private viewing only and not for public exhibition irrespective of whether the public is charged for such exhibition or not. You hereby agree to refrain from further broadcasting or making available the Content provided on the Website to any other person(s), or in any manner communicate such Content to the public.
<br />
In case the Website allows You to download or stream any of the Content therein, You agree that You will not use, sell, transfer or transmit the Content to any person or upload the Content on any other website, webpage or software, which may violate/cause damages or injuries to any rights of JEEOGURU or its affiliates or any third party including privacy rights, publicity rights, and intellectual property rights.
<br />
You may encounter third party applications while using the Website including, without limitation, websites, widgets, software, services that interact with the Website. Your use of these third party applications shall be subject to such third party terms of use or license terms. JEEOGURU shall not be liable for any representations or warranties or obligations made by such third party applications to You under contract or law.
<br />
 </p>
 <div class=" font-size1 font-size16">8.TERMINATION OF SERVICE</div> 
<p class="w3-text-white font-size1 font-size14">
	JEEOGURU reserves the right to immediately terminate, suspend, limit, or restrict Your account or Your use of the Services or access to Content at any time, without notice or liability, if JEEOGURU so determines in its sole discretion, for any reason whatsoever, including that You have breached these Terms of Use, the Privacy Policy, violated any law, rule, or regulation, engaged in any inappropriate conduct, provided false or inaccurate information, or for any other reason. You hereby agree and consent to the above and agree and acknowledge that JEEOGURU can, in its sole discretion, exercise its right in relation to any or all of the above, and that JEEOGURU, its directors, officers, employees, affiliates, agents, contractors, principals or licensors shall not be liable in any manner for the same; and You hereby agree, acknowledge and consent to the same.
</p>
<br />
 <div class=" font-size1 font-size16">9. USER REVIEWS, COMMENTS AND OTHER MATERIAL</div> 
<p class="w3-text-white font-size1 font-size14">
You may have an opportunity to publish, transmit, submit, or otherwise post (collectively, “Post” only reviews or comments (collectively, “User Material”). As it concerns User Material, without prejudice to Your obligation to otherwise comply with applicable laws during the course of using the Services, You agree to hereby comply with any and all applicable laws, as well as any other rules and restrictions that may be set forth herein or on the Website or Services.
<br />
You agree that JEEOGURU shall have the right but have no obligation, to monitor User Material and to restrict or remove User Material that JEEOGURU may determine, in its sole discretion, is inappropriate or for any other reason. You acknowledge that JEEOGURU reserves the right to investigate and take appropriate legal action against anyone who, in JEEOGURU’s sole discretion, violates these Terms of Use, including, but not limited to, terminating their account, terminate, suspend, limit, or use of the Services or access to Content and/or reporting such User Material, conduct, or activity, to law enforcement authorities, in addition to any other available remedies under law or equity. In addition to the restrictions set forth above, You must adhere to the below terms and conditions and not host, display, upload, modify, publish, transmit, update or share any information /material/User Material that:
<br />
(a) belongs to another person and to which You do not have any right to;
<br />
(b) is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, pedophilic, libelous, invasive of another&#39;s privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatsoever;
<br />
(c) harms minors in any way;<br />
(d) infringes any patent, trademark, design, copyright or other proprietary rights;<br />
(e) violates any law for the time being in force;<br />
<br />
(f) deceives or misleads the addressee about the origin of such messages or communicates any information which is grossly offensive or menacing in nature;
<br />
(g) impersonates another person;
<br />
(h) contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer resource;
<br />
(i) threatens the unity, integrity, defense, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognizable offence or prevents investigation of any offence or is insulting any other nation.
<br />
You also represent and warrant that the Posting of Your User Material does not violate any right of any party, including privacy rights, publicity rights, and intellectual property rights.
<br />
You acknowledge that the User Material is not confidential and that You have no expectation of privacy in it.
<br />

By posting the User Material, You hereby grant JEEOGURU a license to use, display, reproduce, distribute, modify, delete from, add to, prepare derivative works of, publicly perform, and publish such User Material worldwide, including on or through any property, in perpetuity, in any media formats and any media channels now known or hereinafter created. The license You grant to JEEOGURU is non-exclusive, royalty-free, irrevocable, and sub licensable. Additionally, JEEOGURU is free to use any ideas, concepts, know-how, or techniques contained within such User Material for any purpose, including, but not limited to, developing, manufacturing, marketing, and providing commercial products and services, including the Services. JEEOGURU’s use of such User Material shall not require any further notice of attribution to You and such use shall be without requirement of any permission from or any payment to You or any other person or entity. You hereby agree and confirm that the provisions of section 19(4) of the Indian Copyright Act, 1957, shall not apply to this license.
<br />
In no event does JEEOGURU assume any responsibility or liability whatsoever for any User Material, and You agree to waive any legal or equitable rights or remedies You may have against JEEOGURU with respect to such User Material.
<br />
If You have any complaints relating to any third party User Material or Content uploaded on the Website, then please contact: <span class="w3-text-amber">feedback@jeeoguru.com </span>, which must bear Your digital signature or a signed written complaint, should include the following information:
<br />
1.Details Of The Objectionable User Material Or Content;
<br />
Details Of The Basis Of The Objection;
<br />
What Relief Is Being Requested;
<br />
All Other Relevant Information Required By Biocine Entertainment To Assess The Complaint.
<br />
JEEOGURU shall on examination of the complaint take all reasonable measures, including taking down the objectionable User Material expeditiously in accordance with applicable law. You agree and acknowledge that JEEOGURU &#39;s responsibility in relation to objectionable User Material is limited to removing them post receipt of Your objections in accordance with these Terms of Useand JEEOGURU shall not be responsible or liable for any other damages or losses incurred by You of any nature whatsoever.
</p>
<br />
<div class=" font-size1 font-size16">10. LINKED DESTINATIONS AND ADVERTISING</div>
  <p class="w3-text-white font-size1 font-size14">
  	Part of this Website/Service contains advertising and other material submitted to JEEOGURU by third parties and/or links to third party sites and third party content. Although display of advertisements on the Website on request is subject to JEEOGURU’s terms and conditions, JEEOGURU expressly disclaims any liability arising out of the usage or viewing of these products or services advertised on the Website or the (third party) content made available / hosted on the third party sites. You agree and acknowledge that JEEOGURU does not endorse or sponsor such third party sites, content, advertising or other material. This Website may contain articles contributed by several individuals. The views are exclusively their own and do not represent the views of JEEOGURU, affiliates and/ or its management. All liability in respect of the above is excluded to the extent permitted by law including any implied terms. Indian law and jurisdiction applies with respect to contents of this Website. While using this website for information purposes or otherwise, users acknowledge and accept the above disclaimer.
<br />
If JEEOGURU provides links or pointers to other websites or destinations, You should not infer or assume that JEEOGURU operates, controls, or is otherwise connected with these other websites or destinations. When You click on a link within the Services, JEEOGURU will not warn You that You have left the Services and are subject to the terms and conditions (including privacy policies) of another website or destination. In some cases, it may be less obvious than others that You have left the Services and reached another website or destination. Please be careful to read the terms of use and privacy policy of any other website or destination before You provide any confidential information or engage in any transactions. You should not rely on these Terms and Conditions and/or Privacy Policy to govern Your use of another website or destination.
<br />
JEEOGURU is not responsible for the content or practices of any website or destination other than the Website, even if it links to the Website and even if the website or destination is operated by a company affiliated or otherwise connected with JEEOGURU. By using the Services, You acknowledge and agree that JEEOGURU is not responsible or liable to You for any content or other materials hosted and served from any website or destination other than the Website. JEEOGURU takes no responsibility for advertisements or any third party material posted on the Website nor does it take any responsibility for the products or services provided by advertisers. Any dealings You have with advertisers found while using the Services are between You and the advertiser, and You agree that JEEOGURU is not liable for any loss or claim that You may have against an advertiser.
<br />
</p>

<br />
<div class=" font-size1 font-size16">11. SUPPORT</div>
  <p class="w3-text-white font-size1 font-size14">
  If You have any questions, complaints or claims with respect to the Website and/or Services, then such correspondence should be directed to the address as given below. Biocine Entertainment
<br />
The contact information –<span class="w3-text-amber">feedback@jeeoguru.com </span> 
</p>
<br />
<div class=" font-size1 font-size16">12. DISCLAIMER OF WARRANTIES</div>
  <p class="w3-text-white font-size1 font-size14">
You agree that use of the Services and the access to the Website is at Your own risk. The Services including the Website, the Content, the video player, User Material and any other materials contained on or provided through the Website are provided “AS IS” and, to the fullest extent permitted by law, are provided without warranties of any kind, either express or implied. Without limiting the foregoing, Biocine Entertainment does not make any warranties of fitness for a particular purpose, title, merchantability, completeness, availability, security, compatibility or non-infringement; or that the Services will be uninterrupted, free of viruses and other harmful components, accurate, error free or reliable.
</p>
<br />

<div class=" font-size1 font-size16">13. LIMITATION OF LIABILITY</div>
  <p class="w3-text-white font-size1 font-size14">
IN NO CASE SHALL BIOCINE ENTERTAINMENT, ITS DIRECTORS, OFFICERS, EMPLOYEES, AFFILIATES, AGENTS, CONTRACTORS, PRINCIPALS, OR LICENSORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, PUNITIVE, SPECIAL, OR CONSEQUENTIAL DAMAGES ARISING FROM YOUR USE OF THE SERVICES OR ANY CONTENT OR MATERIAL THEREOF OR FOR ANY OTHER CLAIM RELATED IN ANY WAY TO YOUR ACCESS OF THE SITE OR USE OF THE SERVICES OR ANY CONTENT OR MATERIAL THEREOF, INCLUDING, BUT NOT LIMITED TO, ANY ERRORS OR OMISSIONS
<br />
IN ANY CONTENT OR MATERIAL, OR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF THE USE OF THE SERVICES OR ANY CONTENT OR MATERIAL THEREOF, EVEN IF ADVISED OF THEIR POSSIBILITY. WHERE THE LAWS DO NOT ALLOW THE EXCLUSION OR THE LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, IN SUCH JURISDICTIONS, BIOCINE ENTERTAINMENT’S LIABILITY SHALL BE LIMITED TO THE EXTENT PERMITTED BY LAW.
</p>
<br />


<div class=" font-size1 font-size16">14. INDEMNITY</div>
  <p class="w3-text-white font-size1 font-size14">
You agree to defend, indemnify and hold harmless JEEOGURU, its affiliates, officers, directors, employees and agents, from and against any and/or all claims, damages, obligations, losses, liabilities, costs or debt, and expenses (including but not limited to attorney’s fees) arising from: (i) Your use of and access to the Services; (ii) Your violation of any term of these Terms and Conditions; (iii) Your violation of any third party right, including without limitation any publicity, privacy, or intellectual property right; (iv) Your breach of any applicable laws; and (v) any unauthorized, improper, illegal or wrongful use of Your Account by any person, including a third party, whether or not authorized or permitted by You. This indemnification obligation will survive the expiry or termination of these Terms and Conditions and Your use of the Service. Reservation of Rights; Waiver. The Service, Software and the Digital Content embody intellectual property that is protected by law. Copyright owners of Digital Content are intended third-party beneficiaries under the Agreement. Our failure to insist upon or enforce your strict compliance with the Agreement will not constitute a waiver of any of our rights.</p>
<br />

<div class=" font-size1 font-size16">15. GOVERNING LAW AND JURISDICTION</div>
  <p class="w3-text-white font-size1 font-size14">
The relationship between You and Biocine Entertainment shall be governed by the laws of India without regard to its conflict of law provisions and for resolution of any dispute arising out of Your use of the Services. Notwithstanding the foregoing, You agree that (i) Biocine Entertainment has the right to bring any proceedings before any court/forum of competent jurisdiction and You irrevocably submit to the jurisdiction of such courts or forum and (ii) any proceeding brought by You shall be exclusively before the courts at Kolkata, India.
</p>
<br />

<div class=" font-size1 font-size16">16. SEVERABILITY</div>
  <p class="w3-text-white font-size1 font-size14">
If any provision of these Terms of Use is held invalid, void, or unenforceable, then that particular provision shall be considered severable from the remaining provisions, and the remaining provisions shall be given full force and effect.
</p>
<br />

<div class=" font-size1 font-size16">17. CHANGES</div>
  <p class="w3-text-white font-size1 font-size14">
JEEOGURU reserves the right, at any time and from time to time, without notice to You, to update, revise, supplement, and otherwise modify these Terms of Use and to impose new or additional rules, policies, terms, or conditions on Your use of the Service. Any material updates, revisions, supplements, modifications, and additional rules, policies, terms, and conditions (collectively referred to in these Terms of Use as “Additional Terms” will be posted on the Website and user interfaces, and will be effective immediately after such posting and thereafter incorporated into these Terms and Conditions. Your continued use of the Services will be deemed to constitute Your acceptance of any and all such Additional Terms.
</p>
<br />


<div class=" font-size1 font-size16">18. SURVIVAL</div>
  <p class="w3-text-white font-size1 font-size14">
You acknowledge that Your representations, undertakings, and warranties and the clauses relating to indemnities, limitation of liability, grant of license, governing law, confidentiality shall survive the efflux of time and the termination of these Terms and Conditions.
</p>
<br />

<div class=" font-size1 font-size16">19. ENTIRE AGREEMENT</div>
  <p class="w3-text-white font-size1 font-size14">
These Terms and Conditions and Privacy Policy constitute the entire agreement between You and Biocine Entertainment  governing Your use of the Services, superseding any prior agreements between You and Biocine Entertainment regarding such use.</p>
<br />
 
<br />


<p class="w3-text-white font-size1 font-size14">Last Updated: August 1, 2018
</p><p class="w3-text-white font-size1 font-size14">© Biocine Entertainment. All rights reserved.</p>